config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'static#home'

  draw(:static)

  resources :cities, only: [:show] do
    collection do
      get 'name', to: 'cities#name', as: 'name'
    end
    resources :reviews
  end

  scope 'compare-cities' do
    get '/', to: 'comparison#index', as: 'compare_cities'
    get '/export', to: 'comparison#export', as: 'export_comparison'
  end

  resources :find, only: [:show, :update]
  resources :favorite_cities, only: [:index, :create, :destroy]
  resources :contacts, only: [:new, :create]
end

app/views/shared/_aleart.html.erb
<% if notice.present? %>
  <div class="notice">
    <div>
      <i class="fa-solid fa-circle-check"></i>
      <%= notice %>
    </div>
    <span class="closebtn" onclick="this.closest('.notice').style.display='none';">&times;</span>
  </div>
<% end %>


<% if alert.present? %>
  <div class="alert">
    <div>
      <i class="fa-solid fa-triangle-exclamation"></i>
      <%= alert %>
    </div>
    <span class="closebtn" onclick="this.closest('.alert').style.display='none';">&times;</span>
  </div>
<% end %>

app/views/shared/_alert.html.erb
<% if notice.present? %>
  <div class="notice">
    <div>
      <i class="fa-solid fa-circle-check"></i>
      <%= notice %>
    </div>
    <span class="closebtn" onclick="this.closest('.notice').style.display='none';">&times;</span>
  </div>
<% end %>


<% if alert.present? %>
  <div class="alert">
    <div>
      <i class="fa-solid fa-triangle-exclamation"></i>
      <%= alert %>
    </div>
    <span class="closebtn" onclick="this.closest('.alert').style.display='none';">&times;</span>
  </div>
<% end %>

app/views/shared/_favorite_city_list.html.erb
<ul class="favoriteCityList">
  <% favorite_cities.each do |favorite_city| %>
    <li class="cityItem" id="<%= dom_id(favorite_city) %>_item">
      <span class="emoji">🇺🇸</span>
      <h3 class="name"><%= link_to favorite_city.city_name, city_path(favorite_city) %></h3>
      <div id="<%= dom_id(favorite_city) %>_btn">
        <%= button_to '-', favorite_city_path(id: favorite_city.id), method: :delete, remote: true, data: { turbo: false }, class: 'deleteBtn custom-tooltip remove' %>
      </div>
    </li>
  <% end %>
</ul>

app/views/shared/_mapbox.html.erb
<div class="map_div">
  <%= js_map [{
                latitude: "41.8789233",
                longitude: "-87.6398049"
              }],
             id: "map",
             zoom: 10,
             controls: true
  %>
</div>

app/views/shared/_mapbox_city.html.erb
<div class="map_div">
  <%= js_map [{
                latitude: city.latitude,
                longitude: city.longitude,
                label: city.city_name,
              }],
             # tooltip: html_link_to(city),
             id: "map",
             tooltips: { hover: false, html: true },
             zoom: 10,
             controls: true
  %>
</div>

app/views/shared/_mapbox_saved_city.html.erb
<div class="map_div" id="map">
  <%= js_map name_cities_path(format: :json),
             id: "cities-map",
             tooltips: { hover: false, html: true},
             zoom: 7,
             controls: true,
             refresh: 300
  %>
</div>

app/views/shared/_mapbox_search_result.html.erb
  <%= js_map name_cities_path(format: :json),
             id: "cities-map",
             markers: { label: 'city_name' },
             tooltips: { hover: false, html: true},
             zoom: 7,
             controls: true,
             refresh: 300
  %>?

app/views/shared/_nav.html.erb
<div class="nav">
  <ul>
    <li>
      <%= link_to 'Search by Priority', find_path(:filter), class: ('active' if current_page?(find_path(:filter))) %>
    </li>
    <li>
      <%= link_to 'City Comparison', name_cities_path, class: ('active' if current_page?(name_cities_path) || current_page?(compare_cities_path)) %>
    </li>
  </ul>
</div>

app/views/shared/_nav_mobile.html.erb
<div class="nav-mobile">
  <ul>
    <li>
      <%= link_to city_map_path, class: ('active' if current_page?(city_map_path)) do %>
        <i class="fa-regular fa-map"></i>
        <div>Map</div>
      <% end %>
    </li>
    <li>
      <%= link_to find_path(:filter), class: ('active' if current_page?(find_path(:filter))) do %>
        <i class="fa-solid fa-magnifying-glass-location"></i>
        <div>Priority Search</div>
      <% end %>
    </li>
    <li>
      <%= link_to name_cities_path, class: ('active' if current_page?(name_cities_path)) do %>
        <i class="fa-solid fa-magnifying-glass"></i>
        <div>Search by Name</div>
      <% end %>
    </li>
    <li>
      <%= link_to favorite_cities_path, class: ('active' if current_page?(favorite_cities_path)) do %>
        <i class="fa-solid fa-thumbtack"></i>
        <div>Saved Cities</div>
      <% end %>
    </li>
    <li>
      <%= link_to compare_cities_path, class: ('active' if current_page?(compare_cities_path)) do %>
        <i class="fa-solid fa-chart-area"></i>
        <div>Compare</div>
      <% end %>
    </li>
  </ul>
</div>

app/views/shared/_rating_by_city.html.erb
<div class="row">
  <% if city.reviews_count > 0 %>
    <%= link_to city_reviews_path(@the_city) do %>
      <div class="flex-div">
      <div><%= display_stars(city) %></div>
      <p><b><%= city.average_rating %></b> (<%= city.reviews_count %>)</p>
      </div>
    <% end %>
  <% else %>
    <%= link_to 'Be the First Reviewer!', new_city_review_path(@the_city) %>
  <% end %>
</div>

app/views/shared/_star.html.erb
<div id="full-stars-example-two">
  <div class="rating-group">
    <input disabled checked class="rating__input rating__input--none" name="rating3" id="rating3-none" value="0" type="radio">
    <label aria-label="1 star" class="rating__label" for="rating3-1"><i class="rating__icon rating__icon--star fa fa-star"></i></label>
    <input class="rating__input" name="rating3" id="rating3-1" value="1" type="radio">
    <label aria-label="2 stars" class="rating__label" for="rating3-2"><i class="rating__icon rating__icon--star fa fa-star"></i></label>
    <input class="rating__input" name="rating3" id="rating3-2" value="2" type="radio">
    <label aria-label="3 stars" class="rating__label" for="rating3-3"><i class="rating__icon rating__icon--star fa fa-star"></i></label>
    <input class="rating__input" name="rating3" id="rating3-3" value="3" type="radio">
    <label aria-label="4 stars" class="rating__label" for="rating3-4"><i class="rating__icon rating__icon--star fa fa-star"></i></label>
    <input class="rating__input" name="rating3" id="rating3-4" value="4" type="radio">
    <label aria-label="5 stars" class="rating__label" for="rating3-5"><i class="rating__icon rating__icon--star fa fa-star"></i></label>
    <input class="rating__input" name="rating3" id="rating3-5" value="5" type="radio">
  </div>
</div>

app/views/shared/_static_nav_mobile.html.erb
<nav class="static-nav-mobile">
  <%= render 'shared/logo' %>
  <div class="hamburger" id="hamburger">
    <div></div>
    <div></div>
    <div></div>
  </div>
  <nav class="hidden-menu">
    <div class="close" id="close">
      <i class="fa-solid fa-xmark"></i>
    </div>
    <ul>
      <div>
        <h1>Welcome, <%= user_signed_in? ? current_user.username : "Guest" %>!👋</h1>
      </div>
      <li>
        <%= link_to 'How to use', about_path %>
      </li>
      <li>
        <%= link_to 'Contact', contact_path %>
      </li>
      <li>
        <%= link_to 'Find my place', find_path(:filter) %>
      </li>
      <hr>
      <li>
        <div class="hidden-menu-btn">
          <% if user_signed_in? %>
            <%= link_to 'Edit', edit_user_registration_path, class: "ctaLink bl" %>
            <%= link_to 'Log Out', destroy_user_session_path, data: { turbo_method: :delete }, class: "ctaLink" %>
          <% else %>
            <%= link_to 'Log In', new_user_session_path, class: "ctaLink" %>
            <%= link_to 'Sign up', new_user_registration_path, class: "ctaLink bl" %>
          <% end %>
        </div>
      </li>
    </ul>
  </nav>
</nav>
<script>
    function toggleMenu() {
        document.querySelector('.hidden-menu').classList.toggle('on');
        document.getElementById('hamburger').classList.toggle('on');
        document.querySelector('body').classList.toggle('on');
    }

    document.getElementById('hamburger').addEventListener('click', toggleMenu);
    document.getElementById('close').addEventListener('click', toggleMenu);
</script>

app/views/shared/_tooltip.html.erb
<div class="tooltip">
  <%= link_to city_path(city), class: 'profile-link' do %>
    <h3>🇺🇸 <%= city.city_name.upcase %></h3>
    <p>Click to See City Info</p>
  <% end %>
</div>

app/views/shared/_user_nav.html.erb
<div class="user">
  <span> <span class="emoji">🙌</span>Welcome,
    <% if user_signed_in? %>
      <%= link_to current_user.username.capitalize, edit_user_registration_path, class: "user-edit" %></span>
      <%= link_to 'Log Out', destroy_user_session_path, method: :delete, data: { turbo: false, confirm: 'Hope you enjoyed your journey with CityFinder.✈️✈' }, class: 'logout-btn' %>
    <% else %>
      Explorer</span>
      <%= link_to 'Log In', new_user_session_path, class: 'logout-btn' %>
    <% end %>
    </div>