config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'static#home'

  draw(:static)

  resources :cities, only: [:show] do
    collection do
      get 'name', to: 'cities#name', as: 'name'
    end
    resources :reviews
  end

  scope 'compare-cities' do
    get '/', to: 'comparison#index', as: 'compare_cities'
    get '/export', to: 'comparison#export', as: 'export_comparison'
  end

  resources :find, only: [:show, :update]
  resources :favorite_cities, only: [:index, :create, :destroy]
  resources :contacts, only: [:new, :create]
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :bigint           not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  remember_created_at    :datetime
#  reset_password_sent_at :datetime
#  reset_password_token   :string
#  user_family_type       :text             default([]), is an Array
#  username               :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
# Indexes
#
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :reviews, class_name: "Review", foreign_key: "user_id", dependent: :destroy
  has_many :favorite_cities, class_name: "FavoriteCity", foreign_key: "user_id", dependent: :destroy
  has_many :cities, through: :favorite_cities
end

app/views/forms/_convenience_filter_form.html.erb
<div class="form-container">
  <div class="form" data-controller="convenience-form">
    <%= form_with url: wizard_path, method: :put, data: { turbo: false }, class: "form", id: "convenience-form" do |form| %>
      <h1><span class="emoji">👋</span>Hi,
        <%= user_signed_in? ? current_user.username.capitalize : 'Explorer' %>!
        <br>What do you need in your city?
      </h1>

      <div class="row">
        <%= form.label :"Must Have" %>
        <%= form.select :"convenience_option", options_for_select([
                                                                    ["Select a factor", ""],
                                                                    ["I'm open to all options 😉", "All"],
                                                                    ["Distance From Work 🚗", "Distance"],
                                                                    ["Metra Station 🚊", "Metra"],
                                                                    ["Grocery Store 🛒", "Grocery"],
                                                                    ["Community 👥", "Community"],
                                                                    ["Gym 🏋️", "Gym"]
                                                                  ]), {}, { class: "select", data: { action: "convenience-form#handlePriorityChange" } } %>

        <div id="distance" class="row" data-convenience-form-target="distance" style="display: none;">
          <%= form.label :place, "From" %>
          <div class="row">
            <%= form.text_field :address, placeholder: "Address" %>
            <div class="flex-div-spread">
              <%= form.text_field :city_name, placeholder: "City Name" %>
              <%= form.text_field :state, placeholder: "Illinois", readonly: true %>
            </div>
          </div>
          <div class="row">
            <%= form.label :distance, "Distance to.." %>
            <%= form.select :distance, options_for_select([["5 miles", 5], ["10 miles", 10], ["20 miles", 20], ["30 miles", 30], ["50 miles", 50]]), {}, { class: "select" } %>
          </div>
        </div>

        <div id="grocery-options" class="grid" data-convenience-form-target="groceryOptions" style="display: none;">
          <% @grocery_names.each do |grocery| %>
            <div>
              <%= form.check_box "grocery[]", { name: "grocery[]" }, grocery, nil %>
              <%= form.label grocery, grocery %>
            </div>
          <% end %>
        </div>

        <div id="gym-options" class="grid" data-convenience-form-target="gymOptions" style="display: none;">
          <% @gym_names.each do |gym| %>
            <div>
              <%= form.check_box "gym[]", { name: "gym[]" }, gym, nil %>
              <%= form.label gym, gym %>
            </div>
          <% end %>
        </div>

        <div id="community" class="row" data-convenience-form-target="community" style="display: none;">
          <%= form.label :"community_language", "Find a community using language" %>
          <%= form.select "community_language", options_for_select([["Select a language", ""]] + @language_names), { include_blank: false }, { class: "select" } %>
        </div>
      </div>

      <%= form.hidden_field :city_ids, value: @city_ids.join(',') %>
      <%= form.submit 'Next', class: 'btn primary large' %>
    <% end %>
  </div>
</div>

app/views/forms/_priority_search_form.html.erb
<div class="form-container">
  <div class="form">
    <%= form_with url: wizard_path, method: :put, data: { turbo: false }, class: "form" do |form| %>
      <h1><%= @greeting %>, <%= user_signed_in? ? current_user.username.capitalize : 'Explorer' %>!
        <span class="emoji">👍</span>
        <br>What matters most to you?
      </h1>

      <% 3.times do |index| %>
        <div class="row">
          <%= form.label :"priority-#{index}", get_label(index) %>
          <%= form.select :"priority-#{index}", options_for_select([
                                                                     ["Select a factor", ""],
                                                                     ["Sale Price (Low to high) 📈", "Sales_low"],
                                                                     ["Sale Price (high to low) 📉", "Sales_high"],
                                                                     ["Rent Price (Low to high) 📈", "rent_low"],
                                                                     ["Rent Price (high to low) 📉", "rent_high"],
                                                                     ["School Rating 🏫", "School"],
                                                                     ["Safety 👮", "Safety"],
                                                                     ["Appreciation Value 📊", "Appreciation"],
                                                                   ]), {}, { class: "select" } %>
        </div>
      <% end %>
      <%= form.hidden_field :city_ids, value: (@city_ids || []).join(',') %>
      <div class="buttons">
        <%= form.submit 'Search', class: 'btn primary' %>
        <%= link_to 'Back', previous_wizard_path, class: 'btn back' %>
      </div>
    <% end %>
  </div>
</div>

app/views/forms/_search_by_name_form.html.erb
<%= search_form_for @q, url: name_cities_path, method: :get do |form| %>
  <div class="search-bar">
    <%= form.text_field :city_name_cont, placeholder: "Search by City Name", class: 'search search-field' %>
    <%= form.submit 'Search', class: 'btn back' %>
  </div>
<% end %>