config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'static#home'

  draw(:static)

  resources :cities, only: [:show] do
    collection do
      get 'name', to: 'cities#name', as: 'name'
    end
    resources :reviews
  end

  scope 'compare-cities' do
    get '/', to: 'comparison#index', as: 'compare_cities'
    get '/export', to: 'comparison#export', as: 'export_comparison'
  end

  resources :find, only: [:show, :update]
  resources :favorite_cities, only: [:index, :create, :destroy]
  resources :contacts, only: [:new, :create]
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_city
  before_action :set_review, only: [:edit, :update, :destroy, :show]
  before_action :authorize_review, only: [:edit, :update, :destroy]


  def index
    @reviews = @city.reviews
  end

  def show
  end

  def new
    @review = @city.reviews.new
  end

  def create
    @review = @city.reviews.new(review_params)
    @review.user = current_user

    if @review.save
      redirect_to city_reviews_path(@city), notice: 'Review was successfully created.'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @review.update(review_params)
      redirect_to city_review_path(@review.city, @review), notice: 'Review was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @review.destroy
    redirect_to city_reviews_path(@review.city), notice: 'Review was successfully destroyed.'
  end

  helper_method :display_stars

  private

  def review_params
    params.require(:review).permit(:pros, :cons, :ratings, { recommend_family_type: [] }, :zipcode)
  end

  def set_city
    @city = City.find(params[:city_id])
  end

  def set_review
    @review = Review.find(params[:id])
  end

  def authorize_review
    authorize @review
  end

  def display_stars(review)
    filled_star_icon = '<span class="fa fa-star checked"></span>'
    empty_star_icon = '<span class="fa fa-star"></span>'
    stars = filled_star_icon * review.ratings + empty_star_icon * (5-review.ratings)
    stars.html_safe
  end
end

app/views/reviews/_form.html.erb
<div class="form">
  <div class="review-form">
    <h1 class="sub-title">Share your thoughts on <%= @city.city_name %>!</h1>
    <%= form_with(model:[@city, @review], local: true) do |form| %>
      <div class="row">
        <%= form.label :pros, "What did you love about #{@city.city_name}?" %>
        <%= form.text_area :pros, placeholder: "I loved..." %>
      </div>
      <div class="row">
        <%= form.label :cons, "What needs improvement in #{@city.city_name}?" %>
        <%= form.text_area :cons, placeholder: "Needs improvement...  " %>
      </div>
      <div class="row">
        <%= form.label :recommend_family_type, "Who do you think would enjoy living here?" %>
        <div class="grid">
          <div class="text no-margin"><%= form.check_box :recommend_family_type, { multiple: true }, 'single', nil %> Single<br></div>
          <div class="text no-margin"><%= form.check_box :recommend_family_type, { multiple: true }, 'married', nil %> Married<br></div>
          <div class="text no-margin"><%= form.check_box :recommend_family_type, { multiple: true }, 'pet', nil %> Pet Owners<br></div>
          <div class="text no-margin"><%= form.check_box :recommend_family_type, { multiple: true }, 'with kid', nil %> Families with Kids<br></div>
          <div class="text no-margin"><%= form.check_box :recommend_family_type, { multiple: true }, 'retired', nil %> Retirees<br></div>
          <div class="text no-margin"><%= form.check_box :recommend_family_type, { multiple: true }, 'remote worker', nil %> Remote Workers<br></div>
          <div class="text no-margin"><%= form.check_box :recommend_family_type, { multiple: true }, 'commuter', nil %> Commuters<br></div>
        </div>
      </div>

      <div class="row" data-controller="star-rating">
        <%= form.label :ratings, "Overall Rating" %>
        <div id="star-rating-input" >
          <% 5.times do |i| %>
            <span class="fa fa-star star-icon" data-star-rating-target="starIcon" data-action="click->star-rating#selectStar" data-value="<%= i + 1 %>"></span>
          <% end %>
        </div>
        <%= form.hidden_field :ratings, id: 'rating-input', 'data-star-rating-target': "rating" %>
      </div>

      <div class="row">
        <%= form.label :zipcode, "Zip Code of #{@city.city_name}" %>
        <%= form.number_field :zipcode, placeholder: "Enter the zip code of #{@city.city_name}..." %>
      </div>

      <div class="buttons">
        <%= form.submit "Submit Your Review", class: "btn primary" %>
        <%= link_to 'Back', '#', class: 'btn back', onclick: 'window.history.back(); return false;' %>
      </div>
    <% end %>
  </div>
</div>

app/views/reviews/_review_list.html.erb
<div class="city review">
  <h1 class="sub-title">Reviews for <%= @city.city_name %></h1>
  <%= render 'score_card', city:@city %>
  <div class="row">
  </div>
  <% @reviews.each do |review| %>
    <div class="flex-div-spread">
      <h2><%= review.author.capitalize %></h2>
      <div>
        <%= display_stars(review) %>
        <%= time_ago_in_words(review.updated_at) %>
      </div>
    </div>
    <div class="row">
      <h6>pros</h6>
      <p><%= review.pros %></p>
    </div>
    <div class="row">
      <h6>cons</h6>
      <p><%= review.cons %></p>
    </div>
    <% unless review.recommend_family_type.nil? %>
      <div class="row">
        <h6>Recommend to</h6>
        <div class="flex-div">
          <p class="tag-color">
            <% review.recommend_family_type.each do |family_type| %>
              <span class="tag-label"><%= family_type %></span>
            <% end %>
          </p>
        </div>
      </div>
    <% end %>

    <% unless review.zipcode.nil? %>
      <div class="flex-div-spread">
        <h6>Zipcode</h6>
        <%= review.zipcode %>
      </div>
    <% end %>

    <% if user_signed_in? && review.user.present? && current_user.id == review.user.id %>
      <div class="buttons-sm">
        <%= link_to 'Edit', edit_city_review_path(@city, review) %>
        <%= link_to 'Delete', city_review_path(@city, review), method: :delete, data: { confirm: 'Are you sure?' } %>
      </div>
    <% end %>
    <hr>
  <% end %>
  <div class="buttons">
    <%= link_to 'New Review', new_city_review_path(@city), class: 'btn primary' %>
    <%= link_to 'Back', '#', class: 'btn back', onclick: 'window.history.back(); return false;' %>
  </div>
</div>

app/views/reviews/_score_card.html.erb
<div class="rating_card">
  <h2>User Rating</h2>
  <div class="flex-div">
    <div>
      <span class="fa fa-star checked"></span>
      <span class="fa fa-star checked"></span>
      <span class="fa fa-star checked"></span>
      <span class="fa fa-star checked"></span>
      <span class="fa fa-star"></span>
    </div>
    <h4> <%= city.average_rating %> average based on <%= city.reviews_count %> reviews</h4>
  </div>
  <hr>
  <% (1..5).reverse_each do |rating| %>
    <% rating_count = city.reviews.where(ratings: rating).count %>
    <% width_percentage = (rating_count.to_f / city.reviews_count * 100).round(2) %>
    <div class="row">
      <div class="flex-div">
        <div class="grid"><%= rating %><span class="fa fa-star checked"></span></div>
        <div class="bar-container">
          <div class="bar" style="width: <%= width_percentage %>%"></div>
        </div>
        <div class="rating-count"><%= rating_count %></div>
      </div>
    </div>
  <% end %>
</div>

app/views/reviews/_sidebar.html.erb
<div class="sidebar">
  <img src="<%= asset_path('logo.png') %>" alt="CityFinder logo" class="logo">
  <%= render 'shared/nav' %>
  <div class="outlet">
    <%= render 'reviews/form' %>
  </div>
  <%= render 'shared/footer' %>
</div>

app/views/reviews/edit.html.erb
<div class="app">
  <div class="sidebar">
    <img src="<%= asset_path('logo.png') %>" alt="CityFinder logo" class="logo">
    <%= render 'shared/nav' %>
    <div class="outlet">
      <h1 class="sub-title">💡Edit Review for <%= @review.city.city_name %></h1>
      <%= render 'form', city: @review.city, review: @review %>
    </div>
    <%= render 'shared/footer' %>
  </div>
  <%= render 'shared/mapbox_city', city:@city %>
  <%= render 'shared/user_nav' %>
  <%= render 'shared/nav_mobile' %>
  <div class="side_mobile_city">
    <%= render 'form', city: @review.city, review: @review %>
  </div>
</div>

app/views/reviews/index.html.erb
<div class="app">
  <div class="sidebar">
    <img src="<%= asset_path('logo.png') %>" alt="CityFinder logo" class="logo">
    <%= render 'shared/nav' %>
    <div class="outlet">
      <%= render 'review_list' %>
    </div>
    <%= render 'shared/footer' %>
  </div>
  <%= render 'shared/mapbox_city', city: @city %>
  <%= render 'shared/user_nav' %>
  <%= render 'shared/nav_mobile' %>
  <div class="side_mobile_city">
    <%= render 'review_list' %>
  </div>
</div>

app/views/reviews/new.html.erb
<div class="app">
  <div class="sidebar">
    <img src="<%= asset_path('logo.png') %>" alt="CityFinder logo" class="logo">
    <%= render 'shared/nav' %>
    <div class="outlet">
      <%= render 'reviews/form' %>
    </div>
    <%= render 'shared/footer' %>
  </div>
  <%= render 'shared/mapbox_city', city:@city %>
  <%= render 'shared/user_nav' %>
  <%= render 'shared/nav_mobile' %>
  <div class="side_mobile_city">
    <%= render 'form' %>
  </div>
</div>

app/views/reviews/show.html.erb
<div class="app">
  <%= render 'sidebar' %>
  <%= render 'shared/mapbox' %>
  <%= render 'shared/user_nav' %>
  <%= render 'shared/nav_mobile' %>
  <div class="side_mobile_city">
    <%= render 'review_list' %>
  </div>
</div>